### ISSUE TITLE
cannot give job vehicles

### ISSUE THREAD

**Issue by Midnight-Vortex** [Musiker15/msk_givevehicle#2]
Hello, 
I entered it like this and it always comes up.

/givejobcar 13 car emshoe ambulance 1 "MED 900"

![grafik](https://github.com/Musiker15/msk_givevehicle/assets/44612764/6430c668-4c24-4358-8826-14e78304a960)
We have the latest ESX on it 1.10.1

can you look for this an fix.

**Comment by waschmaschvanlu** [comment]
as you can see here from the args
`	{name = 'player', help = 'PlayerID', type = 'player'},
	{name = 'type', help = 'Categorie', type = 'string'},
	{name = 'vehicle', help = 'Vehiclename', type = 'string'},
	{name = 'plate', help = '"Plate" (optional)', type = 'string'}`
	
	it wants the player, the type the spawnname and the plate,
	whatever that 1 has to do with there,
	try using
	/givejobcar 13 car emshoe "MED 900"

**Comment by Tiltann** [comment]
`/givejobve. <playerID> <categorie> <carModel> <job> <bool> <plate>`

Is the command, and your  inserting a 1 where  bool is, try using false or true

**Comment by waschmaschvanlu** [comment]
/givejobveh <playerID> <categorie> <carModel> <job> <bool> <plate>

Is the command, and your  inserting a 1 where  bool is, try using false or true

**Comment by Musiker15** [comment]
Fixed in server.lua
